---
# Add PHP repo
- name: Install software-properties-common
  apt: 
   name: software-properties-common
   state: present
- name: Add PHP repository
  apt_repository:
    repo: ppa:ondrej/php
# Update repositories
- name: Update repositories cache
  apt: 
    update_cache: yes

# Install PHP
- name: Install PHP {{php_version}}
  apt: 
    name: "php{{php_version}}"
    state: present
- name: Install PHP FPM
  apt: 
    name: "php{{php_version}}-fpm"
    state: present
- name: Install additional PHP modules #probably gonna have to add some modules
  apt: 
    name: "{{item}}"
    state: present
  loop: ["php{{php_version}}-mysql", "php{{php_version}}-common", "php{{php_version}}-xml", "php{{php_version}}-zip", "php{{php_version}}-gd", "php{{php_version}}-mbstring", "php{{php_version}}-curl", "php{{php_version}}-mcrypt", "php{{php_version}}-phpdbg", "php{{php_version}}-bz2"]

# Install composer
- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
- name: Install Composer
  shell: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

# Install WP CLI, test install with wp --info
- name: Download wp-cli.phar and set it up as wp for all users
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: '0775'
# Change php-fpm config
# /etc/php/8.0/fpm/php.ini update upload_max_filesize = 50M and post_max_size = 64M
- name: Change php-fpm config for upload_max_filesize
  replace:
    path: /etc/php/{{php_version}}/fpm/php.ini
    regexp: "upload_max_filesize.*\n"
    replace: "upload_max_filesize = 50M\n"
  notify:
    - reload php-fpm
- name: Change php-fpm config for post_max_size
  replace:
    path: /etc/php/{{php_version}}/fpm/php.ini
    regexp: "post_max_size.*\n"
    replace: "post_max_size = 64M\n"
  notify:
    - reload php-fpm
- name: Change php-fpm config for memory_limit
  replace:
    path: /etc/php/{{php_version}}/fpm/php.ini
    regexp: "memory_limit.*\n"
    replace: "memory_limit = 512M\n"
  notify:
    - reload php-fpm

- name: Restart and enable PHP-FPM service
  service: name={{item}} state=restarted enabled=yes
  loop: ["php{{php_version}}-fpm"]